const data = [
  {
    words: [
      "Effective",
      "communication",
      "requires",
      "careful",
      "consideration",
      "of",
      "the",
      "audience",
    ],
    sentences: [
      "Effective communication of the audience requires careful consideration",
      "Careful consideration of the audience is required for effective communication",
      "The audience requires careful consideration for effective communication",
      "Careful consideration is necessary for the effective communication of the audience",
      "Effective communication requires the careful consideration of the audience",
      "The careful consideration of the audience is essential for effective communication",
      "For effective communication, the audience requires careful consideration",
      "Effective communication needs careful consideration of the audience",
      "The audience's careful consideration is required for effective communication",
      "Effective communication involves the careful consideration of the audience",
      "Effective communication requires careful consideration of the audience",
    ],
  },
  {
    words: [
      "Reading",
      "books",
      "improves",
      "vocabulary",
      "and",
      "comprehension",
      "skills",
    ],
    sentences: [
      "Reading books improves vocabulary and comprehension skills",
      "Books improve vocabulary and comprehension skills through reading",
      "Vocabulary and comprehension skills are improved by reading books",
      "Comprehension skills improve with vocabulary through reading books",
      "Reading improves comprehension and vocabulary skills from books",
      "Reading improves skills and vocabulary through books",
      "Vocabulary is improved by reading books enhancing comprehension skills",
      "Skills and vocabulary improve with reading books",
      "Books enhance comprehension skills and vocabulary through reading",
      "Comprehension and vocabulary are improved by reading books",
      "Reading enhances comprehension skills and improves vocabulary from books",
      "Books improve comprehension and vocabulary through reading them",
      "Skills in comprehension and vocabulary are improved by reading books",
      "Through reading books enhance comprehension skills and vocabulary",
      "Vocabulary improvement and enhanced comprehension skills come from reading books",
    ],
  },
  {
    words: ["Traveling", "broadens", "horizons", "and", "enriches", "lives"],
    sentences: [
      "Traveling broadens horizons and enriches lives",
      "Traveling broadens horizons",
      "Traveling enriches lives",
      "Broadens horizons and enriches lives",
      "Traveling broadens and enriches lives",
      "Traveling enriches and broadens horizons",
      "Traveling enriches lives and broadens horizons",
      "Lives and horizons and traveling broadens enriches",
      "Traveling and lives and horizons enriches broadens",
      "Horizons and lives enriches and traveling broadens",
    ],
  },
  {
    words: [
      "Exercise",
      "boosts",
      "energy",
      "levels",
      "and",
      "improves",
      "health",
    ],
    sentences: [
      "Exercise boosts energy levels and improves health",
      "Energy levels are boosted and health improved by exercise",
      "Health is improved and energy levels boosted through exercise",
      "Exercise improves health and boosts energy levels",
      "Boosting energy levels and improving health come from exercise",
    ],
  },
  {
    words: [
      "Eating",
      "balanced",
      "meals",
      "promotes",
      "wellness",
      "and",
      "vitality",
    ],
    sentences: [
      "Eating balanced meals promotes wellness and vitality",
      "Balanced meals promote wellness and enhance vitality",
      "Wellness and vitality are promoted by eating balanced meals",
      "Eating balanced meals enhances wellness and boosts vitality",
      "Vitality and wellness are improved by consuming balanced meals",
    ],
  },
  {
    words: [
      "Regular",
      "practice",
      "enhances",
      "skills",
      "and",
      "builds",
      "confidence",
    ],
    sentences: [
      "Regular practice enhances skills and builds confidence",
      "Skills are enhanced and confidence built through regular practice",
      "Confidence is built and skills enhanced by regular practice",
      "Regular practice builds confidence and enhances skills",
      "Enhancing skills and building confidence come from regular practice",
    ],
  },
];
